
version: '3.8'

services:
  postgres:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/
  client:
    depends_on:
      - server
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - 3000:3000
    env_file: ./frontend/.env.production
  server:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile
      context: ./backend
    working_dir: /usr/src/app
    entrypoint: ["/bin/bash", "./entrypoint.sh"]
    ports:
      - 3001:3001
    env_file: ./backend/.env.production
volumes:
  pg_data:
